// Curated starter dream purchases with high quality imagery and realistic data

export const INITIAL_SAMPLE_DREAMS = [
  {
    name: 'Royal Enfield Super Meteor 650',
    brand: 'Royal Enfield',
    category: 'Vehicles',
    type: 'BIG_DREAM',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80',
    sourceUrl: 'https://www.royalenfield.com',
    sourceName: 'Royal Enfield Official',
    listedPrice: 4200,
    finalPrice: 3950,
    currency: 'USD',
    priority: 'S_TIER',
    status: 'SAVING',
    amountSaved: 2150,
    notes: 'Stellar Marine Blue edition with touring windscreen and deluxe engine guards. The ultimate highway cruiser.',
    specs: '648cc Parallel Twin Engine, 47 BHP, Dual-Channel ABS, Showa 43mm USD Forks, Tripper Navigation.',
    isCurrentQuest: true,
  },
  {
    name: 'Custom Cyberpunk Liquid-Cooled Battlestation',
    brand: 'Custom Build',
    category: 'Electronics & PC',
    type: 'BIG_DREAM',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80',
    sourceUrl: 'https://pcpartpicker.com',
    sourceName: 'PC Part Picker',
    listedPrice: 3800,
    finalPrice: 3600,
    currency: 'USD',
    priority: 'S_TIER',
    status: 'PLANNING',
    amountSaved: 900,
    notes: 'Black & Gold custom loop aesthetics inspired by Black Bulls Anti-Magic grimoire.',
    specs: 'Ryzen 9 9950X, RTX 5080, 64GB DDR5 6400MHz, 4TB Gen5 NVMe, Lian Li O11 Dynamic EVO.',
    isCurrentQuest: false,
  },
  {
    name: 'Sony WH-1000XM6 Wireless Noise Cancelling Headphones',
    brand: 'Sony',
    category: 'Audio & Tech',
    type: 'SMALL_DREAM',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=80',
    sourceUrl: 'https://electronics.sony.com',
    sourceName: 'Sony Store',
    listedPrice: 399,
    finalPrice: 349,
    currency: 'USD',
    priority: 'A_TIER',
    status: 'READY_TO_BUY',
    amountSaved: 349,
    notes: 'Flagship ANC headphones for deep focus work sessions and anime OST listening.',
    specs: 'Industry-leading noise cancellation, LDAC high-res audio, 30h battery life, multi-point connection.',
    isCurrentQuest: false,
  },
  {
    name: 'Asta 5-Leaf Grimoire Demon Slayer 1/7 Scale Statue',
    brand: 'Prime 1 Studio',
    category: 'Anime & Figures',
    type: 'SMALL_DREAM',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1000&q=80',
    sourceUrl: 'https://www.prime1studio.com',
    sourceName: 'Prime 1 Studio',
    listedPrice: 580,
    finalPrice: 550,
    currency: 'USD',
    priority: 'A_TIER',
    status: 'SAVING',
    amountSaved: 200,
    notes: 'Epic dynamic sculpt showing Black Asta half-demon mode with glowing anti-magic aura effects.',
    specs: 'Hand-painted polystone, LED illuminated base, 42cm height, numbered limited edition certificate.',
    isCurrentQuest: false,
  },
  {
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    brand: 'Keychron',
    category: 'Gaming',
    type: 'SMALL_DREAM',
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1000&q=80',
    sourceUrl: 'https://www.keychron.com',
    sourceName: 'Keychron Official',
    listedPrice: 219,
    finalPrice: 199,
    currency: 'USD',
    priority: 'B_TIER',
    status: 'DREAMING',
    amountSaved: 50,
    notes: 'Full CNC aluminum body, double-gasket design, Banana tactile switches.',
    specs: '75% Layout, QMK/VIA programmable, Bluetooth 5.1 & Type-C, Hot-swappable PCB.',
    isCurrentQuest: false,
  },
  {
    name: 'Black Clover Manga Complete Box Set (Vol. 1-36+)',
    brand: 'Viz Media / Shueisha',
    category: 'Manga & Books',
    type: 'SMALL_DREAM',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80',
    sourceUrl: 'https://www.viz.com',
    sourceName: 'Viz Media',
    listedPrice: 280,
    finalPrice: 240,
    currency: 'USD',
    priority: 'B_TIER',
    status: 'PURCHASED',
    amountSaved: 240,
    notes: 'The complete physical collection of Yuki Tabata’s masterpiece for the bookshelf altar.',
    specs: 'Paperback English translations, exclusive art booklet, collector storage box.',
    isCurrentQuest: false,
    datePurchased: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: 'Sony Alpha 7 IV Full-Frame Mirrorless Camera',
    brand: 'Sony',
    category: 'Cameras & Gear',
    type: 'BIG_DREAM',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    sourceUrl: 'https://electronics.sony.com',
    sourceName: 'B&H Photo Video',
    listedPrice: 2498,
    finalPrice: 2298,
    currency: 'USD',
    priority: 'A_TIER',
    status: 'SAVING',
    amountSaved: 1200,
    notes: 'For cinematic photo and 4K60 video creation with GM lenses.',
    specs: '33MP Exmor R sensor, BIONZ XR engine, 759-point AF with real-time Eye AF.',
    isCurrentQuest: false,
  },
  {
    name: 'Ergonomic Herman Miller Embody Gaming Chair',
    brand: 'Herman Miller x Logitech G',
    category: 'Home & Workspace',
    type: 'BIG_DREAM',
    image: 'https://images.unsplash.com/photo-1580481077197-22709e3e3b7b?auto=format&fit=crop&w=1200&q=80',
    sourceUrl: 'https://store.hermanmiller.com',
    sourceName: 'Herman Miller',
    listedPrice: 1795,
    finalPrice: 1550,
    currency: 'USD',
    priority: 'B_TIER',
    status: 'PLANNING',
    amountSaved: 400,
    notes: 'Ultimate ergonomic posture support for long coding and gaming quests.',
    specs: 'Pixelated Support matrix, copper-infused foam layer, fully adjustable armrests, 12-year warranty.',
    isCurrentQuest: false,
  }
];
