import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAuth } from '@/lib/auth';
import { db } from '@/lib/db';
import { evaluateAchievements } from '@/lib/achievements';

const dreamSchema = z.object({
  id: z.string().optional(),
  name: z.string().min(1),
  brand: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  variant: z.string().optional().nullable(),
  category: z.string().default('General'),
  type: z.string().default('BIG_DREAM'),
  image: z.string().optional().nullable(),
  sourceUrl: z.string().optional().nullable(),
  officialUrl: z.string().optional().nullable(),
  marketplaceUrl: z.string().optional().nullable(),
  sourceName: z.string().optional().nullable(),
  verifiedSource: z.string().optional().nullable(),
  sourceType: z.string().optional().nullable(),
  listedPrice: z.number().default(0),
  finalPrice: z.number().default(0),
  finalCheckoutPrice: z.number().optional(),
  shippingCost: z.number().default(0),
  mandatoryFees: z.number().default(0),
  currency: z.string().default('INR'),
  priority: z.string().default('A_TIER'),
  status: z.string().default('DREAMING'),
  amountSaved: z.number().default(0),
  monthlyContribution: z.number().optional().nullable(),
  targetDate: z.union([z.string(), z.date()]).optional().nullable(),
  notes: z.string().optional().nullable(),
  specs: z.string().optional().nullable(),
  isCurrentQuest: z.boolean().default(false),
  priceConfidence: z.string().default('VERIFIED'),
  priceBreakdown: z.union([z.string(), z.record(z.unknown())]).optional().nullable(),
  locationState: z.string().optional().nullable(),
  locationCity: z.string().optional().nullable(),
  isManualOverride: z.boolean().default(false),
  manualOverride: z.boolean().default(false),
  previousPrice: z.number().optional().nullable(),
  availability: z.string().optional().nullable(),
  lastChecked: z.union([z.string(), z.date()]).optional().nullable(),
  dateAdded: z.union([z.string(), z.date()]).optional(),
  datePurchased: z.union([z.string(), z.date()]).optional().nullable(),
});

const importPayloadSchema = z.object({
  app: z.string().optional(),
  data: z.object({
    dreams: z.array(dreamSchema).optional(),
    financialMonths: z.array(z.record(z.unknown())).optional(),
    incomeEntries: z.array(z.record(z.unknown())).optional(),
    expenses: z.array(z.record(z.unknown())).optional(),
    savingsAllocations: z.array(z.record(z.unknown())).optional(),
    purchaseTransactions: z.array(z.record(z.unknown())).optional(),
  }),
});

export async function POST(req: NextRequest) {
  try {
    const session = await requireAuth(req);
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json().catch(() => ({}));
    const parseResult = importPayloadSchema.safeParse(body);

    if (!parseResult.success) {
      return NextResponse.json(
        {
          error: 'Invalid Life Quest backup file structure. Please ensure the file was generated by Life Quest.',
          details: parseResult.error.errors[0]?.message,
        },
        { status: 400 }
      );
    }

    const { dreams = [] } = parseResult.data.data;
    let importedDreamsCount = 0;

    for (const d of dreams) {
      const breakdownStr =
        typeof d.priceBreakdown === 'object' && d.priceBreakdown !== null
          ? JSON.stringify(d.priceBreakdown)
          : d.priceBreakdown || null;

      const finalPriceVal = d.finalPrice || d.listedPrice || 0;
      const finalCheckoutVal = d.finalCheckoutPrice || finalPriceVal;
      const isManual = Boolean(d.manualOverride || d.isManualOverride);

      // Upsert dream by id
      if (d.id) {
        await db.dreamPurchase.upsert({
          where: { id: d.id },
          create: {
            id: d.id,
            name: d.name,
            brand: d.brand || null,
            model: d.model || null,
            variant: d.variant || null,
            category: d.category,
            type: d.type,
            image: d.image || null,
            sourceUrl: d.sourceUrl || null,
            officialUrl: d.officialUrl || null,
            marketplaceUrl: d.marketplaceUrl || null,
            sourceName: d.sourceName || null,
            verifiedSource: d.verifiedSource || d.sourceName || null,
            sourceType: d.sourceType || 'OFFICIAL',
            listedPrice: d.listedPrice || finalPriceVal,
            finalPrice: finalPriceVal,
            finalCheckoutPrice: finalCheckoutVal,
            shippingCost: d.shippingCost || 0,
            mandatoryFees: d.mandatoryFees || 0,
            currency: d.currency,
            priority: d.priority,
            status: d.status,
            amountSaved: d.amountSaved,
            notes: d.notes || null,
            specs: d.specs || null,
            isCurrentQuest: d.isCurrentQuest,
            priceConfidence: d.priceConfidence,
            priceBreakdown: breakdownStr,
            locationState: d.locationState || null,
            locationCity: d.locationCity || null,
            isManualOverride: isManual,
            manualOverride: isManual,
            previousPrice: d.previousPrice || null,
            lastChecked: d.lastChecked ? new Date(d.lastChecked) : new Date(),
            dateAdded: d.dateAdded ? new Date(d.dateAdded) : new Date(),
            datePurchased: d.datePurchased ? new Date(d.datePurchased) : null,
          },
          update: {
            name: d.name,
            brand: d.brand || null,
            model: d.model || null,
            variant: d.variant || null,
            category: d.category,
            type: d.type,
            image: d.image || null,
            sourceUrl: d.sourceUrl || null,
            officialUrl: d.officialUrl || null,
            marketplaceUrl: d.marketplaceUrl || null,
            sourceName: d.sourceName || null,
            verifiedSource: d.verifiedSource || d.sourceName || null,
            sourceType: d.sourceType || 'OFFICIAL',
            listedPrice: d.listedPrice || finalPriceVal,
            finalPrice: finalPriceVal,
            finalCheckoutPrice: finalCheckoutVal,
            shippingCost: d.shippingCost || 0,
            mandatoryFees: d.mandatoryFees || 0,
            currency: d.currency,
            priority: d.priority,
            status: d.status,
            amountSaved: d.amountSaved,
            notes: d.notes || null,
            specs: d.specs || null,
            priceConfidence: d.priceConfidence,
            priceBreakdown: breakdownStr,
            locationState: d.locationState || null,
            locationCity: d.locationCity || null,
            isManualOverride: isManual,
            manualOverride: isManual,
            previousPrice: d.previousPrice || null,
            lastChecked: d.lastChecked ? new Date(d.lastChecked) : new Date(),
            datePurchased: d.datePurchased ? new Date(d.datePurchased) : null,
          },
        });
      } else {
        await db.dreamPurchase.create({
          data: {
            name: d.name,
            brand: d.brand || null,
            model: d.model || null,
            variant: d.variant || null,
            category: d.category,
            type: d.type,
            image: d.image || null,
            sourceUrl: d.sourceUrl || null,
            officialUrl: d.officialUrl || null,
            marketplaceUrl: d.marketplaceUrl || null,
            sourceName: d.sourceName || null,
            verifiedSource: d.verifiedSource || d.sourceName || null,
            sourceType: d.sourceType || 'OFFICIAL',
            listedPrice: d.listedPrice || finalPriceVal,
            finalPrice: finalPriceVal,
            finalCheckoutPrice: finalCheckoutVal,
            shippingCost: d.shippingCost || 0,
            mandatoryFees: d.mandatoryFees || 0,
            currency: d.currency,
            priority: d.priority,
            status: d.status,
            amountSaved: d.amountSaved,
            notes: d.notes || null,
            specs: d.specs || null,
            isCurrentQuest: d.isCurrentQuest,
            priceConfidence: d.priceConfidence,
            priceBreakdown: breakdownStr,
            locationState: d.locationState || null,
            locationCity: d.locationCity || null,
            isManualOverride: isManual,
            manualOverride: isManual,
            previousPrice: d.previousPrice || null,
            lastChecked: d.lastChecked ? new Date(d.lastChecked) : new Date(),
            dateAdded: d.dateAdded ? new Date(d.dateAdded) : new Date(),
            datePurchased: d.datePurchased ? new Date(d.datePurchased) : null,
          },
        });
      }
      importedDreamsCount++;
    }

    // Re-evaluate achievements with imported data
    await evaluateAchievements();

    return NextResponse.json({
      success: true,
      message: `Successfully imported ${importedDreamsCount} dream quests.`,
      importedCount: importedDreamsCount,
    });
  } catch (error) {
    console.error('Import data error:', error);
    return NextResponse.json(
      { error: 'Failed to process import data. Ensure valid JSON format.' },
      { status: 500 }
    );
  }
}
